version: '3.8'

services:
  web:
    image: docker.io/fountain0/survey_group8:latest
    container_name: survey_app
    command: /bin/bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 survey_group8.wsgi:application"
    restart: always
    volumes:
      - static_data:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  static_data: {}  # Define the 'vol' volume at the top level
  postgres_data: {}  # Define the 'postgres_data' volume at the top level

