# Generated by Django 5.1.1 on 2024-10-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('t', 'Survey Taker'), ('c', 'Survey Creator')], max_length=10),
        ),
    ]
